### ISSUE TITLE
READMe.md mentions 'npm run test' which doesn't work.

### ISSUE THREAD

**Issue by AndrewKL** [focusOtter/microsaas-backend#1]
ran

```
npm install
npm run test
```
and got the following error message
```
loandrew@88665a173757 microsaas-backend % npm run test
npm ERR! Missing script: "test"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

running '> npm run'. showed the following results

```
loandrew@88665a173757 microsaas-backend % npm run
Scripts available in backend-saas-starter@0.1.0 via `npm run-script`:
  build
    tsc
  watch
    tsc -w
  cdk
    cdk
  build:appsyncFunctions
    node build.mjs
  create:amplifyWebhook
    aws amplify create-webhook --app-id "$APP_ID" --branch-name "$BRANCH_NAME"
  create:SSMSecret
    aws secretsmanager create-secret --name "$SECRET_NAME" --secret-string "$SECRET_VALUE"
  create:ParameterStoreSecret
    aws ssm put-parameter --name "$SECRET_NAME" --value "$SECRET_VALUE" --type SecureString
  list:deployOutput
    aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[].Outputs[]"
  graphql:codegen
    cd lib/api/graphql && npx @aws-amplify/cli codegen && cd ../../../
```

**Comment by mtliendo** [comment]
Hey! Thanks for the issue. This project doesn't contain any tests, so the command is not populated.

**Comment by AndrewKL** [comment]
So i checked that package and there's no unit tests for the resolvers so I gave a shot at it by doing the following
> npm install --save-dev jest
created a file at
```
 Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   package.json
        new file:   test/api/graphql/functions/Query.getRecipe.test.ts
```
with the following test
```
import { request, response } from '../../../../lib/api/graphql/functions/Query.getUser'
import {GetUserQueryVariables} from "../../../../lib/api/graphql/API";

test("request", () => {
   const ctx =  {
      arguments: {
         id: "id-str"
      },
      identity: {
         sourceId: "123.123.123.123",
         username: "usernm",
         sub: "guid"

      }
   }
   //Context<GetUserQueryVariables>

   const resp = request((ctx as any))
   // above fails due to...

   /*
   Cannot read properties of undefined (reading 'toMapValues')
TypeError: Cannot read properties of undefined (reading 'toMapValues')
    at request (/Users/loandrew/git/microsaas-backend/lib/api/graphql/functions/Query.getUser.ts:17:22)
    at Object.<anonymous> (/Users/loandrew/git/microsaas-backend/test/api/graphql/functions/Query.getRecipe.test.ts:24:22)
    at Promise.then.completed (/Users/loandrew/git/microsaas-backend/node_modules/jest-circus/build/utils.js:300:28)
    */

   /*

    */
   // DynamoDBGetItemRequest
})
```
Unfortunately this doesn't seem to work due to the fact that we only have type script definitions instead of the full util class.
